import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const links = [
  { href: "/", label: "Home" },
  { href: "/docs", label: "docs" },
  { href: "/about", label: "About" }
];

export default function RootLayout({
  children
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex items-center">
            {links.map(({ href, label }) => (
              <li key={href}>
                <Link href={href} className="mr-6">
                  {label}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
